code = {
    "Applied Mathematics I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Physics-I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Chemistry": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Computing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Communicative English Skills": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Civic and Ethical Education": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Health &Physical Education I": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Logic and Critical Thinking": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Applied Mathematics II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "General Physics II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fundamentals of Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Engineering Drawing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Basic Writing Skills": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Data Structure and Algorithm": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electronic Circuit": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Applied Mathematics III": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fundamental of Electrical Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Principle of Economics": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Object Oriented Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Discrete Mathematics for CSE": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Digital Logic Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Database Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electronic circuit II": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "System Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Graphics": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Algorithms": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Probability and Random Process": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Fund. of software Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Architecture & Organization": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Operating System": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Data Communication & Computer Networks": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Artificial": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "SOftware Requirement Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Web Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Advanced Programming": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Formal Language and automata Theory": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Engineering Research and Development Methodology": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Multimedia Tech.": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Software Design and Architecture": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Mobile Computing and Applications": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Signals and Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Data mining": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to NLP": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer System and security": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Programming languages": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Project Management": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Law": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Compiler Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Digital Signal Processing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "VLSI Design": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Electrical Network Analysis and synthesis": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Computer Vision": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Semester Project": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Seminar": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Distributed Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Wireless mobile Networks": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Image Processing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Human Computer Interaction": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Audio & Video Production": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Advanced Network": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Control Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "B.Sc. Project": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Entrepreneurship for Engineers": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Games & Animation": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Special Topics in Computer Science & Engineering": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Real time and Embedded Systems": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Software Quality & Testing": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Computer Ethics and Social Issues": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME",
    "Introduction to Robotics and Industrial Automation": "BQACAgQAAxkBAAPkYdwq-A1RtnU7FQABHlBcUqTU-VWNAAIfCgAC62_hUr0AAcTBU9A4ZSME"
}

d = {"Applied Mathematics I": "Math1101",
     "General Physics-I": "Phys1101",
     "General Chemistry": "Chem1101",
     "Introduction to Computing": "CSE1101",
     "Communicative English Skills": "ENG1011",
     "Civic and Ethical Education": "LAR1011",
     "Health &Physical Education I": "HPEd1011",
     "Logic and Critical Thinking": "LAR1012", "Applied Mathematics II": "Math1102",
     "General Physics II": "Phys1102",
     "Fundamentals of Programming": "CSE1102",
     "Engineering Drawing": "DME1102",
     "Basic Writing Skills": "ENG1102",
     "Health &Physical Education I": "HPEd1012",
     "Logic and Critical Thinking": "LAR1012",
     "Civic and Ethical Education": "LAR1011", "Data Structure and Algorithm": "CSE2101",
     "Electronic Circuit": "ECE2101",
     "Applied Mathematics III": "MATH2051",
     "Fundamental of Electrical Engineering": "PCE2101",
     "Principle of Economics": "SOS311", "Object Oriented Programming": "CSE2202",
     "Discrete Mathematics for CSE": "CSE2206",
     "Digital Logic Design": "ECE3204",
     "Database Systems": "CSE3207",
     "Electronic circuit II": "ECE2202",
     "System Programming": "CSE2320",
     "Algorithms": "CSE3211",
     "Probability and Random Process": "ECE3103",
     "Fund. of software Engineering": "CSE3205",
     "Computer Architecture & Organization": "CSE3203",
     "Operating System": "CSE3204",
     "Data Communication & Computer Networks": "CSE3221",
     "Introduction to Artificial": "CSE3206",
     "SOftware Requirement Engineering": "CSE3308",
     "Web Programming": "CSE3306",
     "Advanced Programming": "CSE3312", "Formal Language and automata Theory": "CSE4224",
     "Engineering Research and Development Methodology": "CSE4221",
     "Multimedia Tech.": "CSE4303",
     "Software Design and Architecture": "CSE4309",
     "Mobile Computing and Applications": "CSE4311",
     "Signals and Systems": "ECE2204",
     "Introduction to Data mining": "CSE5317",
     "Introduction to NLP": "CSE5321",
     "Computer System and security": "Unkown", "Programming languages": "CSE4202",
     "Project Management": "CSE4302",
     "Introduction to Law": "Unknown",
     "Compiler Design": "CSE4310",
     "Digital Signal Processing": "ECE3205",
     "VLSI Design": "ECE5307",
     "Electrical Network Analysis and synthesis": "PCE3201",
     "Introduction to Computer Vision": "CSE4312", "Semester Project": "CSE5201",
     "Seminar": "CSE5205",
     "Distributed Systems": "CSE5307",
     "Wireless mobile Networks": "CSE5309",
     "Image Processing": "CSE5311",
     "Human Computer Interaction": "CSE5313",
     "Introduction to Audio & Video Production": "CSE5315",
     "Advanced Network": "CSE5319",
     "Introduction to Control Systems": "PCE3204", "B.Sc. Project": "CSE5202",
     "Entrepreneurship for Engineers": "SOSC412",
     "Computer Games & Animation": "CSE5304",
     "Special Topics in Computer Science & Engineering": "CSE5306",
     "Real time and Embedded Systems": "CSE5308",
     "Software Quality & Testing": "CSE5310",
     "Computer Ethics and Social Issues": "CSE5312",
     "Introduction to Robotics and Industrial Automation": "PCE5308"

     }
e = {}
for i in code:
    e[d[i]] = code[i]
